project_id = "qfgudhbrjfjmbamwsfuj"

[functions.ms365-auth]
verify_jwt = false

[functions.manage-roles]
verify_jwt = false

[functions.categorise-transactions]
verify_jwt = false

[functions.scan-bill]
verify_jwt = false

[functions.ai-insights]
verify_jwt = false